language: php

php:
    - 7.2
    - 7.3
    - 7.4.22

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    # allow_failures:
    # only one build will send the coverage, this'll speed up other one
    # include:

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update
    - mkdir tests/upload/dst
    - chmod +w tests/upload/dst
    - mkdir tests/upload/tmp
    - chmod +w tests/upload/tmp

install:
    - composer install --no-interaction --prefer-dist -o

script:
    - XDEBUG_MODE=coverage vendor/bin/phpunit

after_script:
    - travis_retry php vendor/bin/php-coveralls -v
